
# .github/workflows/linter.yml

name: Linter

on:
	# git action triggers when pushed or pulled to/from the branch
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
# pipleline job is called Linter
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
		# specifies which version of ubuntu
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
			# description of command and running linter
      - name: Installing linter
        run: npm install eslint
      - name: Running linter
        run: ./node_modules/.bin/eslint .
