
# .github/workflows/unitTest.yml

name: Unit-Test

on:
	# git action triggers when pushed or pulled to/from the branch
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
# pipleline job is called UnitTest
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
		# specifies which version of ubuntu
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
			# description of command and running tests
      - name: Install Testing Tools
        run: npm install
      - name: Run Test Suite
        run: npm test
